2024-11-09 20:39:50.096700: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 20:39:50.116203: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 20:39:50.122311: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-09 20:39:50.137326: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-09 20:39:51.221258: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Token indices sequence length is longer than the specified maximum sequence length for this model (1026 > 1024). Running this sequence through the model will result in indexing errors
Namespace(config='config/agnews.yaml', model='llama3', seed=1, nshot=4, test_data_path='', output='experiment/agnews', generate=True, ngram=3, max_generation_length=128, temperature=2.0, do_sample=True, topk=20, train_sample_mode='')
override n-shot from 1 to 4
{'train_data_path': 'data/agnews/train.jsonl', 'test_data_path': 'data/agnews/dev_subsample.jsonl', 'tokenizer_path': 'distilgpt2', 'n_shot': 4, 'label_mapping': {'1': 'world', '2': 'sports', '3': 'business', '4': 'technology'}, 'corpus_params': {'sentence_1_str': 'sentence', 'label_str': 'label'}, 'template': "f'input: {sentence_1}\\ntype: {label_text}\\n\\n'", 'sample_mode': 'balance', 'sentence_pair': False, 'permutation_max_size': 24}
allowed tokens <|begin_of_text|>input: 
type: 

 world sports business technology
Use subset of full permutations
train_prompts_length:  965
  0%|          | 0/128 [00:00<?, ?it/s]  1%|          | 1/128 [00:05<11:12,  5.29s/it]  2%|▏         | 2/128 [00:10<10:30,  5.00s/it]  2%|▏         | 3/128 [00:14<10:07,  4.86s/it]  3%|▎         | 4/128 [00:19<09:58,  4.83s/it]  4%|▍         | 5/128 [00:24<09:39,  4.71s/it]  5%|▍         | 6/128 [00:28<09:20,  4.59s/it]  5%|▌         | 7/128 [00:33<09:30,  4.72s/it]  6%|▋         | 8/128 [00:38<09:35,  4.80s/it]2024-11-09 20:40:35.882632: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 20:40:35.902696: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 20:40:35.908812: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-09 20:40:35.923473: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-09 20:40:37.021235: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  7%|▋         | 9/128 [00:43<09:37,  4.85s/it]Namespace(config='config/agnews.yaml', model='llama3', seed=1, nshot=4, test_data_path='', output='experiment/agnews', generate=True, ngram=3, max_generation_length=128, temperature=2.0, do_sample=True, topk=20, train_sample_mode='')
override n-shot from 1 to 4
{'train_data_path': 'data/agnews/train.jsonl', 'test_data_path': 'data/agnews/dev_subsample.jsonl', 'tokenizer_path': 'distilgpt2', 'n_shot': 4, 'label_mapping': {'1': 'world', '2': 'sports', '3': 'business', '4': 'technology'}, 'corpus_params': {'sentence_1_str': 'sentence', 'label_str': 'label'}, 'template': "f'input: {sentence_1}\\ntype: {label_text}\\n\\n'", 'sample_mode': 'balance', 'sentence_pair': False, 'permutation_max_size': 24}
Traceback [1;36m(most recent call last)[0m:
[0m  File [0;32m/workspaces/ordered-prompt/main.py:161[0m
    main(corpus_config=corpus_config, args=args)[0m
[0m  File [0;32m/workspaces/ordered-prompt/main.py:98[0m in [0;35mmain[0m
    model = init_model(args)[0m
[0m  File [0;32m/workspaces/ordered-prompt/main.py:38[0m in [0;35minit_model[0m
    model = model.to('cuda', non_blocking=True)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1145[0m in [0;35mto[0m
    return self._apply(convert)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:820[0m in [0;35m_apply[0m
    param_applied = fn(param)[0m
[1;36m  File [1;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1143[1;36m in [1;35mconvert[1;36m
[1;33m    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)[1;36m
[1;31mOutOfMemoryError[0m[1;31m:[0m CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 79.14 GiB total capacity; 1.08 GiB already allocated; 27.31 MiB free; 1.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

> [0;32m/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py[0m(1143)[0;36mconvert[0;34m()[0m
[0;32m   1141 [0;31m                return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
[0m[0;32m   1142 [0;31m                            non_blocking, memory_format=convert_to_format)
[0m[0;32m-> 1143 [0;31m            [0;32mreturn[0m [0mt[0m[0;34m.[0m[0mto[0m[0;34m([0m[0mdevice[0m[0;34m,[0m [0mdtype[0m [0;32mif[0m [0mt[0m[0;34m.[0m[0mis_floating_point[0m[0;34m([0m[0;34m)[0m [0;32mor[0m [0mt[0m[0;34m.[0m[0mis_complex[0m[0;34m([0m[0;34m)[0m [0;32melse[0m [0;32mNone[0m[0;34m,[0m [0mnon_blocking[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m   1144 [0;31m[0;34m[0m[0m
[0m[0;32m   1145 [0;31m        [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_apply[0m[0;34m([0m[0mconvert[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
ipdb> Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1300, in __call__
    self.debugger()
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1275, in debugger
    self.pdb.interaction(None, exc)
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/debugger.py", line 464, in interaction
    OldPdb.interaction(self, frame, tb)
  File "/usr/local/lib/python3.10/pdb.py", line 348, in interaction
    self._cmdloop()
  File "/usr/local/lib/python3.10/pdb.py", line 313, in _cmdloop
    self.cmdloop()
  File "/usr/local/lib/python3.10/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor

Original exception was:
Traceback (most recent call last):
  File "/workspaces/ordered-prompt/main.py", line 161, in <module>
    main(corpus_config=corpus_config, args=args)
  File "/workspaces/ordered-prompt/main.py", line 98, in main
    model = init_model(args)
  File "/workspaces/ordered-prompt/main.py", line 38, in init_model
    model = model.to('cuda', non_blocking=True)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 79.14 GiB total capacity; 1.08 GiB already allocated; 27.31 MiB free; 1.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
python main.py --config config/agnews.yaml      --nshot 4 --model llama3 --output experiment/agnews --seed 1      --ngram 3 --generate --temperature 2.0 --topk 20 --do_sample
  8%|▊         | 10/128 [00:48<09:31,  4.85s/it]2024-11-09 20:40:47.562494: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 20:40:47.581734: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 20:40:47.587778: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-09 20:40:47.602436: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-09 20:40:48.697759: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  9%|▊         | 11/128 [00:52<09:15,  4.75s/it]Namespace(config='config/agnews.yaml', model='llama3', seed=1, nshot=4, test_data_path='', output='experiment/agnews', generate=True, ngram=5, max_generation_length=128, temperature=2.0, do_sample=True, topk=20, train_sample_mode='')
override n-shot from 1 to 4
{'train_data_path': 'data/agnews/train.jsonl', 'test_data_path': 'data/agnews/dev_subsample.jsonl', 'tokenizer_path': 'distilgpt2', 'n_shot': 4, 'label_mapping': {'1': 'world', '2': 'sports', '3': 'business', '4': 'technology'}, 'corpus_params': {'sentence_1_str': 'sentence', 'label_str': 'label'}, 'template': "f'input: {sentence_1}\\ntype: {label_text}\\n\\n'", 'sample_mode': 'balance', 'sentence_pair': False, 'permutation_max_size': 24}
Traceback [1;36m(most recent call last)[0m:
[0m  File [0;32m/workspaces/ordered-prompt/main.py:161[0m
    main(corpus_config=corpus_config, args=args)[0m
[0m  File [0;32m/workspaces/ordered-prompt/main.py:98[0m in [0;35mmain[0m
    model = init_model(args)[0m
[0m  File [0;32m/workspaces/ordered-prompt/main.py:38[0m in [0;35minit_model[0m
    model = model.to('cuda', non_blocking=True)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1145[0m in [0;35mto[0m
    return self._apply(convert)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:797[0m in [0;35m_apply[0m
    module._apply(fn)[0m
[0m  File [0;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:820[0m in [0;35m_apply[0m
    param_applied = fn(param)[0m
[1;36m  File [1;32m~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1143[1;36m in [1;35mconvert[1;36m
[1;33m    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)[1;36m
[1;31mRuntimeError[0m[1;31m:[0m CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


> [0;32m/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py[0m(1143)[0;36mconvert[0;34m()[0m
[0;32m   1141 [0;31m                return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
[0m[0;32m   1142 [0;31m                            non_blocking, memory_format=convert_to_format)
[0m[0;32m-> 1143 [0;31m            [0;32mreturn[0m [0mt[0m[0;34m.[0m[0mto[0m[0;34m([0m[0mdevice[0m[0;34m,[0m [0mdtype[0m [0;32mif[0m [0mt[0m[0;34m.[0m[0mis_floating_point[0m[0;34m([0m[0;34m)[0m [0;32mor[0m [0mt[0m[0;34m.[0m[0mis_complex[0m[0;34m([0m[0;34m)[0m [0;32melse[0m [0;32mNone[0m[0;34m,[0m [0mnon_blocking[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m   1144 [0;31m[0;34m[0m[0m
[0m[0;32m   1145 [0;31m        [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_apply[0m[0;34m([0m[0mconvert[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
ipdb> Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1300, in __call__
    self.debugger()
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1275, in debugger
    self.pdb.interaction(None, exc)
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/debugger.py", line 464, in interaction
    OldPdb.interaction(self, frame, tb)
  File "/usr/local/lib/python3.10/pdb.py", line 348, in interaction
    self._cmdloop()
  File "/usr/local/lib/python3.10/pdb.py", line 313, in _cmdloop
    self.cmdloop()
  File "/usr/local/lib/python3.10/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor

Original exception was:
Traceback (most recent call last):
  File "/workspaces/ordered-prompt/main.py", line 161, in <module>
    main(corpus_config=corpus_config, args=args)
  File "/workspaces/ordered-prompt/main.py", line 98, in main
    model = init_model(args)
  File "/workspaces/ordered-prompt/main.py", line 38, in init_model
    model = model.to('cuda', non_blocking=True)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/vscode/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

python main.py --config config/agnews.yaml      --nshot 4 --model llama3 --output experiment/agnews --seed 1      --ngram 5 --generate --temperature 2.0 --topk 20 --do_sample
  9%|▉         | 12/128 [00:57<08:58,  4.64s/it]Traceback [1;36m(most recent call last)[0m:
[1;36m  File [1;32m/workspaces/ordered-prompt/augment.py:65[1;36m
[1;33m    data = pickle.load(open(fn, "rb"))[1;36m
[1;31mFileNotFoundError[0m[1;31m:[0m [Errno 2] No such file or directory: 'generate*'

> [0;32m/workspaces/ordered-prompt/augment.py[0m(65)[0;36m<module>[0;34m()[0m
[0;32m     63 [0;31m[0;32mif[0m [0m__name__[0m [0;34m==[0m [0;34m"__main__"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m     64 [0;31m    [0mfn[0m [0;34m=[0m [0msys[0m[0;34m.[0m[0margv[0m[0;34m[[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m---> 65 [0;31m    [0mdata[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mopen[0m[0;34m([0m[0mfn[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m     66 [0;31m    [0mcfg[0m [0;34m=[0m [0measydict[0m[0;34m.[0m[0mEasyDict[0m[0;34m([0m[0mdata[0m[0;34m[[0m[0;34m'config'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m     67 [0;31m    [0mgeneration_data[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;34m'result'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
ipdb> Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1300, in __call__
    self.debugger()
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1275, in debugger
    self.pdb.interaction(None, exc)
  File "/home/vscode/.local/lib/python3.10/site-packages/IPython/core/debugger.py", line 464, in interaction
    OldPdb.interaction(self, frame, tb)
  File "/usr/local/lib/python3.10/pdb.py", line 348, in interaction
    self._cmdloop()
  File "/usr/local/lib/python3.10/pdb.py", line 313, in _cmdloop
    self.cmdloop()
  File "/usr/local/lib/python3.10/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor

Original exception was:
Traceback (most recent call last):
  File "/workspaces/ordered-prompt/augment.py", line 65, in <module>
    data = pickle.load(open(fn, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'generate*'
mkdir: cannot create directory ‘ckpt’: File exists
cat: 'augment_*.jsonl': No such file or directory
mv: cannot stat 'augment_*.jsonl': No such file or directory
python main.py --config config/agnews.yaml      --nshot 4 --model llama3 --output experiment/agnews --seed 1 --test_data_path experiment/agnews/dev_agnews_4_shot_llama3_seed1.jsonl;
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
2024-11-09 20:40:58.307301: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 20:40:58.326398: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 20:40:58.332352: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-09 20:40:58.346858: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
 10%|█         | 13/128 [01:01<08:54,  4.65s/it]2024-11-09 20:40:59.441812: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Namespace(config='config/agnews.yaml', model='llama3', seed=1, nshot=4, test_data_path='experiment/agnews/dev_agnews_4_shot_llama3_seed1.jsonl', output='experiment/agnews', generate=False, ngram=0, max_generation_length=128, temperature=1.0, do_sample=False, topk=-1, train_sample_mode='')
override test data path from data/agnews/dev_subsample.jsonl to experiment/agnews/dev_agnews_4_shot_llama3_seed1.jsonl
override n-shot from 1 to 4
{'train_data_path': 'data/agnews/train.jsonl', 'test_data_path': 'experiment/agnews/dev_agnews_4_shot_llama3_seed1.jsonl', 'tokenizer_path': 'distilgpt2', 'n_shot': 4, 'label_mapping': {'1': 'world', '2': 'sports', '3': 'business', '4': 'technology'}, 'corpus_params': {'sentence_1_str': 'sentence', 'label_str': 'label'}, 'template': "f'input: {sentence_1}\\ntype: {label_text}\\n\\n'", 'sample_mode': 'balance', 'sentence_pair': False, 'permutation_max_size': 24}
0it [00:00, ?it/s]0it [00:00, ?it/s]
 11%|█         | 14/128 [01:06<09:02,  4.76s/it]The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
2024-11-09 20:41:06.382785: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 20:41:06.402736: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 20:41:06.408869: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-09 20:41:06.423430: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-09 20:41:07.513840: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
 12%|█▏        | 15/128 [01:11<09:06,  4.83s/it]Namespace(config='config/agnews.yaml', model='llama3', seed=1, nshot=4, test_data_path='', output='experiment/agnews', generate=False, ngram=0, max_generation_length=128, temperature=1.0, do_sample=False, topk=-1, train_sample_mode='')
override n-shot from 1 to 4
{'train_data_path': 'data/agnews/train.jsonl', 'test_data_path': 'data/agnews/dev_subsample.jsonl', 'tokenizer_path': 'distilgpt2', 'n_shot': 4, 'label_mapping': {'1': 'world', '2': 'sports', '3': 'business', '4': 'technology'}, 'corpus_params': {'sentence_1_str': 'sentence', 'label_str': 'label'}, 'template': "f'input: {sentence_1}\\ntype: {label_text}\\n\\n'", 'sample_mode': 'balance', 'sentence_pair': False, 'permutation_max_size': 24}
  0%|          | 0/256 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (1026 > 1024). Running this sequence through the model will result in indexing errors
 12%|█▎        | 16/128 [01:16<09:07,  4.89s/it] 13%|█▎        | 17/128 [01:21<08:59,  4.86s/it]